

INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Nina Brown', 'nina@gmail.com', '$2a$10$kGhfTWpQbIqE01d0ChIrbOwDq2rJ.XVai09mTD3f9OhnphZ/QjaNC');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Admin', 'admin@gmail.com', '$2a$10$kGhfTWpQbIqE01d0ChIrbOwDq2rJ.XVai09mTD3f9OhnphZ/QjaNC');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('leia', 'leia@gmail.com', '$2a$10$kGhfTWpQbIqE01d0ChIrbOwDq2rJ.XVai09mTD3f9OhnphZ/QjaNC');

INSERT INTO TB_ROLE (role_name) VALUES ('ROLE_OPERATOR');
INSERT INTO TB_ROLE (role_name) VALUES ('ROLE_ADMIN');

INSERT INTO TB_USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO TB_USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);

